import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { db } from '@/firebase/client';
import { doc, getDoc } from 'firebase/firestore';

export default function Home() {
  const [name, setName] = useState('');

  function loadName(): void {
    if (!name) {
      getDoc(doc(db, 'user', 'doc1'))
        .then((d) => setName(d.data()?.name))
        .catch((e) => console.log('e', e));
    }
  }

  return (
    <>
      <Head>
        <title>{`Printinkz ${name && `- ${name}`}`}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {name && (
          <div className={styles.description}>
            <p>{name}</p>
          </div>
        )}
        <div className={styles.center} onClick={loadName}>
          <div className={styles.thirteen}>
            <Image
              src='/printinkz.svg'
              alt='Printinkz Logo'
              width={250}
              height={250}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}

