import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { Nunito } from '@next/font/google';

const nunito = Nunito({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Printinkz</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Link
          className={styles.description}
          href='https://merchants.printinkz.com'
        >
          <h3 className={nunito.className}>👉🏻 Merchants Dashboard</h3>
        </Link>
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <Image
              src='/printinkz.svg'
              alt='Printinkz Logo'
              width={200}
              height={200}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}

